server:
  port: 8081

spring:
  security:
    oauth2:
      client:
        registration:
          Demo-realm:
            client-id: service1
            client-secret: 48186d05-7799-4610-9ea9-055e5931b4c5
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/demo-realm
        provider:
          Demo-realm:
            authorization-uri: http://localhost:9000/auth/realms/Demo-realm/protocol/openid-connect/auth
            token-uri: http://localhost:9000/auth/realms/Demo-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:9000/auth/realms/Demo-realm/protocol/openid-connect/userinfo
            user-name-attribute: preferred_username
logging:
  level:
    root: DEBUG
