server:
    port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/Demo-realm
          jwk-set-uri: http://localhost:9000/auth/realms/Demo-realm/protocol/openid-connect/certs
logging:
  level:
    root: DEBUG
